name: Run Go Tests

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go Test with SQLite

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Download Go Modules
        run: go mod download

      - name: Run Tests
        env:
          DATABASE_URL: file::memory:?cache=shared
        run: go test ./... -v
